---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by nikolay.karlov.
--- DateTime: 06/06/2019 11:17
---

local m = {}

function m.init()
    -- create space
    local u = box.schema.space.create('user', {
        if_not_exists = true
    })

    u:format({
        { name = "id", type = "unsigned" },
        { name = "name", type = "string" },
        { name = "age", type = "unsigned" }
    })

    u:create_index('pk', { if_not_exists = true })
    u:create_index('age', {
        parts = {
            {'name', 'string'},
            {'age', 'unsigned'}
        },
        unique = false,
        if_not_exists = true})
end

-- global function is a stored procedure
function m.test(s)
    return s
end

-- create new user or increment age for an existing one
function m.create_or_update(id, name, age)
    local u = box.space.user
    local t = u:get({id})
    if t ~= nil then
        return u:update({id},{{"+", 3, 1}})
    end
    return u:insert({id, name, age})
end

return m